### Cadastrar automovel
POST https://localhost:5001/concessionaria/automovel/cadastrar
Content-Type: application/json

{
    "Id": "1",
    "Marca": "VW",
    "Modelo": "Fusquinha",
    "Ano": "1962",
    "Preco": "2.99"
}

### Listar automovel
GET https://localhost:5001/concessionaria/automovel/listar